---
- hosts: masters,workers
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Teardown kube config
      file:
        path: /etc/kubernetes
        state: absent
    - name: Teardown etcd
      file:
        path: /var/lib/etcd
        state: absent
    - name: Teardown cni
      file:
        path: /etc/cni/net.d
        state: absent
    - name: Remove interfaces
      shell: |
        ip link delete cni0 || exit 0
        ip link delete flannel.1 || exit 0
    - name: Reset kubeadm
      shell: kubeadm reset -f
    - name: Remove packages
      apt:
        state: absent
        purge: true
        name:
          - kubelet
          - kubeadm
          - kubectl
          - containerd.io
          - helm
