---
- hosts: masters[0]
  tasks:
    - name: show all the hosts matching the pattern, i.e. all but the group www
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
        - all:!masters
