---
- hosts: workers
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    # - name: ensures /run/flannel dir exists
    #   file:
    #     path: /run/flannel
    #     state: directory

    # - name: Copy subnet.env to workers
    #   ansible.builtin.template:
    #     src: assets/subnet.env
    #     dest: /run/flannel/subnet.env

    - name: Copy join command to worker nodes.
      become: yes
      become_method: sudo
      become_user: root
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777

    - name: Join the Worker nodes with the master.
      become: yes
      become_method: sudo
      become_user: root
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not

    - debug:
        msg: "{{ joined_or_not.stdout }}"

    - pause: seconds=30

- hosts: workers
  remote_user: ansible
  connection: ssh

  tasks:
    - name: Update pod CIDR on worker nodes (for some reason this needs doing?)
      delegate_to: "{{ groups['masters'][0] }}"
      shell: kubectl patch node {{ ansible_host }} -p '{"spec":{"podCIDR":"{{ pod_cidr }}"}}'

- hosts: masters
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks:
    - name: Configure kubectl command auto-completion.
      lineinfile:
        dest: /home/{{ ansible_user }}/.bashrc
        line: "source <(kubectl completion bash)"
        insertafter: EOF

- hosts: masters[0]

  tasks:
    - name: Untaint master so it can run workloads
      shell: kubectl taint nodes kube00 node-role.kubernetes.io/control-plane:NoSchedule-
