apiVersion: skaffold/v4beta2 latest
kind: Config
metadata:
  name: kubernetes

build:
  artifacts: []

deploy:
  helm:
    releases:
      - name: dashy
        namespace: dashy
        createNamespace: true
        chartPath: charts/dashy
        valuesFiles:
        - values/dashy/values.yaml

