apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-prod
  namespace: default
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: stuartfyfe86@gmail.com
    privateKeySecretRef:
      name: issuer-prod-key
    solvers:
    - http01:
        ingress:
          class: nginx
